
<!DOCTYPE html> 
<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">-->

<head>
<title></title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<META HTTP-EQUIV="Pragma" CONTENT="no-cache">

<meta name="viewport" content="width=device-width"/>

</head>

<body >

<div id="headertop">
  <header id="custom_header">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr> 
        <td width="25%"><a href=" https://www.skinmdnow.com/" target="blank"><img src="{{ asset('images/logo.png') }}" width="258"></a></td>
        <td width="50%" style='text-align:center;padding-top:2px;'></td>
      </tr>
    </table>

<div id="pageTerms" class="panel" data-header="custom_header" data-load="pageTermsOnLoad" style="padding:10px;text-align:justify;display:block; width:600px; margin:0 auto 36px auto;" > 
<br>
<br>
<br>
 
      <!-- 2nd col start -->
      
      <h2 align="center">NOTICE OF PRIVACY PRACTICES</h2>
      <div align="center">Skin<sup>md</sup> Now 310 N Derby Ln Ste 72, N. Sioux City, SD 57049</div>
      <div align="center">Amy Chabra, CEO 605.550.0606</div>
      <p><strong><br>
        Effective Date: January 1, 2013</strong><br>
                THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.</p>
      <p style="font-style:italic; line-height:15px; font-size:12px;">We understand the importance of privacy and are committed to maintaining the confidentiality of your medical information. We make a record of the medical care we provide and may receive such records from others. We use these records to provide or enable other health care providers to provide quality medical care, to obtain payment for services provided to you as allowed by your health plan and to enable us to meet our professional and legal obligations to operate Skin MD Now properly. We are required by law to maintain the privacy of protected health information, to provide individuals with notice of our legal duties and privacy practices with respect to protected health information, and to notify affected individuals following a breach of unsecured protected health information. This notice describes how we may use and disclose your medical information. It also describes your rights and our legal obligations with respect to your medical information. If you have any questions about this Notice, please contact Amy Chabra,
                
                info@skinMDnow.com, 605.550.0606.</p>
      <h3 align="center">TABLE OF CONTENTS</h3>
      <ol type="A">
                <li>How Skin MD Now May Use or Disclose Your Health Information..........</li>
                <li>When Skin MD Now May Not Use or Disclose Your Health Information..........</li>
                <li>Your Health Information Rights..........</li>
                <ol>
          <li>Right to Request Special Privacy Protections</li>
          <li>Right to Request Confidential Communications</li>
          <li>Right to Inspect and Copy</li>
          <li>Right to Amend or Supplement</li>
          <li>Right to an Accounting of Disclosures</li>
          <li>Right to a Paper or Electronic Copy of this Notice</li>
        </ol>
                <li>Changes to this Notice of Privacy Practices..........</li>
                <li>Complaints ..........</li>
              </ol>
      <p>&nbsp;</p>
      <p><strong>A. How Skin MD Now May Use or Disclose Your Health Information</strong></p>
      <p>Skin MD Now collects health information about you and stores it in an electronic health record/personal health record. This is your medical record. The medical record is the property of Skin MD Now, but the information in the medical record belongs to you. The law permits us to use or disclose your health information for the following purposes:</p>
      <ol>
                <li><span style="text-decoration:underline">Treatment.</span> <br>
                We use medical information about you to provide your medical care. We disclose medical information to our employees and others who are involved in providing the care you need. For example, we may share your medical information with other physicians or other health care providers who will provide services that we do not provide. Or we may share this information with a pharmacist who needs it to dispense a prescription to you, or a laboratory that performs a test. We may also disclose medical information to members of your family or others who can help you when you are sick or injured, or after you die.</li>
                <li><span style="text-decoration:underline">Payment.</span> <br>
                We use and disclose medical information about you to obtain payment for the services we provide. For example, we give your health plan the information it requires before it will pay us. We may also disclose information to other health care providers to assist them in obtaining payment for services they have provided to you.</li>
                <li><span style="text-decoration:underline">Health Care Operations.</span> <br>
                We may use and disclose medical information about you to operate Skin MD Now. For example, we may use and disclose this information to review and improve the quality of care we provide, or the competence and qualifications of our professional staff. Or we may use and disclose this information to get your health plan to authorize services or referrals. We may also use and disclose this information as necessary for medical reviews, legal services and audits, including fraud and abuse detection and compliance programs and business planning and management. We may also share your medical information with our "business associates," such as our billing service, that perform administrative services for us. We have a written contract with each of these business associates that contains terms requiring them and their subcontractors to protect the confidentiality and security of your protected health information. We may also share your information with other health care providers, health care clearinghouses or health plans that have a relationship with you, when they request this information to help them with their quality assessment and improvement activities, their patient-safety activities, their population-based efforts to improve health or reduce health care costs, their protocol development, case management or care-coordination activities, their review of competence, qualifications and performance of health care professionals, their training programs, their accreditation, certification or licensing activities, or their health care fraud and abuse detection and compliance efforts. We may also share medical information about you with the other health care providers, health care clearinghouses and health plans that participate with us in "organized health care arrangements" (OHCAs) for any of the OHCAs' health care operations. OHCAs include hospitals, physician organizations, health plans, and other entities which collectively provide health care services. A listing of the OHCAs we participate in is available from the Privacy Official.</li>
                <li><span style="text-decoration:underline">Notification and Communication With Family.</span> <br>
                We may disclose your health information to notify or assist in notifying a family member, your personal representative or another person responsible for your care about your location, your general condition or, unless you had instructed us otherwise, in the event of your death. In the event of a disaster, we may disclose information to a relief organization so that they may coordinate these notification efforts. We may also disclose information to someone who is involved with your care or helps pay for your care. If you are able and available to agree or object, we will give you the opportunity to object prior to making these disclosures, although we may disclose this information in a disaster even over your objection if we believe it is necessary to respond to the emergency circumstances. If you are unable or unavailable to agree or object, our health professionals will use their best judgment in communication with your family and others.</li>
                <li><span style="text-decoration:underline">Marketing.</span> <br>
                Provided we do not receive any payment for making these communications, we may contact you to give you information about products or services related to your treatment, case management or care coordination, or to direct or recommend other treatments, therapies, health care providers or settings of care that may be of interest to you. We may similarly describe products or services provided by this practice and tell you which health plans this practice participates in. We may also encourage you to maintain a healthy lifestyle and get recommended tests, participate in a disease management program, provide you with small gifts, tell you about government sponsored health programs or encourage you to purchase a product or service when we see you, for which we may be paid. Finally, we may receive compensation which covers our cost of reminding you to take and refill your medication, or otherwise communicate about a drug or biologic that is currently prescribed for you. We will not otherwise use or disclose your medical information for marketing purposes or accept any payment for other marketing communications without your prior written authorization. The authorization will disclose whether we receive any compensation for any marketing activity you authorize, and we will stop any future marketing activity to the extent you revoke that authorization.</li>
                <li><span style="text-decoration:underline">Sale of Health Information.</span> <br>
                  We will not sell your health information without your prior 
          written authorization. The authorization will disclose that we will receive compensation for your health information if you authorize us to sell it, and we will stop any future sales of your information to the extent that you revoke that authorization.</li>
                <li><span style="text-decoration:underline">Required by Law.</span> <br>
                As required by law, we will use and disclose your health information, but we will limit our use or disclosure to the relevant requirements of the law. When the law requires us to report abuse, neglect or domestic violence, or respond to judicial or administrative proceedings, or to law enforcement officials, we will further comply with the requirement set forth below concerning those activities.</li>
                <li><span style="text-decoration:underline">Public Health.</span> <br>
                We may, and are sometimes required by law, to disclose your health information to public health authorities for purposes related to: preventing or controlling disease, injury or disability; reporting child, elder or dependent adult abuse or neglect; reporting domestic violence; reporting to the Food and Drug Administration problems with products and reactions to medications; and reporting disease or infection exposure. When we report suspected elder or dependent adult abuse or domestic violence, we will inform you or your personal representative promptly unless in our best professional judgment, we believe the notification would place you at risk of serious harm or would require informing a personal representative we believe is responsible for the abuse or harm.</li>
                <li><span style="text-decoration:underline">Health Oversight Activities.</span> <br>
                We may, and are sometimes required by law, to disclose your health information to health oversight agencies during the course of audits, investigations, inspections, licensure and other proceedings, subject to the limitations imposed by law.</li>
                <li><span style="text-decoration:underline">Judicial and Administrative Proceedings.</span> <br>
                We may, and are sometimes required by law, to disclose your health information in the course of any administrative or judicial proceeding to the extent expressly authorized by a court or administrative order. We may also disclose information about you in response to a subpoena, discovery request or other lawful process if reasonable efforts have been made to notify you of the request and you have not objected, or if your objections have been resolved by a court or administrative order.</li>
                <li><span style="text-decoration:underline">Law Enforcement.</span> <br>
                We may, and are sometimes required by law, to disclose your health information to a law enforcement official for purposes such as identifying or locating a suspect, fugitive, material witness or missing person, complying with a court order, warrant, grand jury subpoena and other law enforcement purposes.</li>
                <li><span style="text-decoration:underline">Coroners.</span> <br>
                We may, and are often required by law, to disclose your health information to coroners in connection with their investigations of deaths.</li>
                <li><span style="text-decoration:underline">Organ or Tissue Donation.</span> <br>
                We may disclose your health information to organizations involved in procuring, banking or transplanting organs and tissues.</li>
                <li><span style="text-decoration:underline">Public Safety.</span> <br>
                We may, and are sometimes required by law, to disclose your health information to appropriate persons in order to prevent or lessen a serious and imminent threat to the health or safety of a particular person or the general public.</li>
                <li><span style="text-decoration:underline">Proof of Immunization.</span> <br>
                We will disclose proof of immunization to a school that is required to have it before admitting a student where you have agreed to the disclosure on behalf of yourself or your dependent.</li>
                <li><span style="text-decoration:underline">Specialized Government Functions.</span> <br>
                  We may disclose your health information for military or
          national security purposes or to correctional institutions or law enforcement officers that have you in their lawful custody.</li>
                <li><span style="text-decoration:underline">Workers’ Compensation.</span> <br>
                We may disclose your health information as necessary to comply with workers’ compensation laws. For example, to the extent your care is covered by workers' compensation, we will make periodic reports to your employer about your condition. We are also required by law to report cases of occupational injury or occupational illness to the employer or workers' compensation insurer.</li>
                <li><span style="text-decoration:underline">Change of Ownership.</span> <br>
                In the event that Skin MD Now is sold or merged with another organization, your health information/record will become the property of the new owner, although you will maintain the right to request that copies of your health information be transferred to another physician or medical group.</li>
                <li><span style="text-decoration:underline">Breach Notification.</span> <br>
                In the case of a breach of unsecured protected health information, we will notify you as required by law. If you have provided us with a current e-mail address, we may use e-mail to communicate information related to the breach. In some circumstances our business associate may provide the notification. We may also provide notification by other methods as appropriate.</li>
                <li><span style="text-decoration:underline">Research.</span> <br>
                We may disclose your health information to researchers conducting research with respect to which your written authorization is not required as approved by an Institutional Review Board or privacy board, in compliance with governing law.</li>
              </ol>
      <p><strong>B. When Skin MD Now May Not Use or Disclose Your Health Information</strong></p>
      <p>Except as described in this Notice of Privacy Practices, Skin MD Now will, consistent with its legal obligations, not use or disclose health information which identifies you without your written authorization. If you do authorize Skin MD Now to use or disclose your health information for another purpose, you may revoke your authorization in writing at any time.</p>
      <p><strong>C. Your Health Information Rights</strong></p>
      <ol>
                <li><span style="text-decoration:underline">Right to Request Special Privacy Protections.</span> <br>
                You have the right to request restrictions on certain uses and disclosures of your health information by a written request specifying what information you want to limit, and what limitations on our use or disclosure of that information you wish to have imposed. If you tell us not to disclose information to your commercial health plan concerning health care items or services for which you paid for in full out-of-pocket, we will abide by your request, unless we must disclose the information for treatment or legal reasons. We reserve the right to accept or reject any other request, and will notify you of our decision.</li>
                <li><span style="text-decoration:underline">Right to Request Confidential Communications.</span> <br>
                You have the right to request that you receive your health information in a specific way or at a specific location. For example, you may ask that we send information to a particular e-mail account or to your work address. We will comply with all reasonable requests submitted in writing which specify how or where you wish to receive these communications.</li>
                <li><span style="text-decoration:underline">Right to Inspect and Copy.</span> <br>
                You have the right to inspect and copy your health information, with limited exceptions. To access your medical information, you must submit a written request detailing what information you want access to, whether you want to inspect it or get a copy of it, and if you want a copy, your preferred form and format. We will provide copies in your requested form and format if it is readily producible, or we will provide you with an alternative format you find acceptable, or if we can’t agree and we maintain the record in an electronic format, your choice of a readable electronic or hardcopy format. We will also send a copy to any other person you designate in writing. We will charge a reasonable fee which covers our costs for labor, supplies, postage, and if requested and agreed to in advance, the cost of preparing an explanation or summary. We may deny your request under limited circumstances. If we deny your request to access your child's records or the records of an incapacitated adult you are representing because we believe allowing access would be reasonably likely to cause substantial harm to the patient, you will have a right to appeal our decision. If we deny your request to access your psychotherapy notes, you will have the right to have them transferred to another mental health professional.</li>
                <li><span style="text-decoration:underline">Right to Amend or Supplement.</span> <br>
                You have a right to request that we amend your health information that you believe is incorrect or incomplete. You must make a request to amend in writing, and include the reasons you believe the information is inaccurate or incomplete. We are not required to change your health information, and will provide you with information about Skin MD Now 's denial and how you can disagree with the denial. We may deny your request if we do not have the information, if we did not create the information (unless the person or entity that created the information is no longer available to make the amendment), if you would not be permitted to inspect or copy the information at issue, or if the information is accurate and complete as is. If we deny your request, you may submit a written statement of your disagreement with that decision, and we may, in turn, prepare a written rebuttal. All information related to any request to amend will be maintained and disclosed in conjunction with any subsequent disclosure of the disputed information.</li>
                <li><span style="text-decoration:underline">Right to an Accounting of Disclosures.</span> <br>
                You have a right to receive an accounting of disclosures of your health information made by Skin MD Now , except that Skin MD Now does not have to account for the disclosures provided to you or pursuant to your written authorization, or as described in paragraphs 1 (treatment), 2 (payment), 3 (health care operations), 6 (notification and communication with family) and 18 (specialized government functions) of Section A of this Notice of Privacy Practices or disclosures for purposes of research or public health which exclude direct patient identifiers, or which are incident to a use or disclosure otherwise permitted or authorized by law, or the disclosures to a health oversight agency or law enforcement official to the extent Skin MD Now has received notice from that agency or official that providing this accounting would be reasonably likely to impede their activities.</li>
                <li><span style="text-decoration:underline">Right to a Paper or Electronic Copy of this Notice.</span> <br>
                You have a right to notice of our legal duties and privacy practices with respect to your health information, including a right to a paper copy of this Notice of Privacy Practices, even if you have previously requested its receipt by e-mail.</li>
              </ol>
      <p>If you would like to have a more detailed explanation of these rights or if you would like to exercise one or more of these rights, contact our Privacy Officer listed at the top of this Notice of Privacy Practices.</p>
      <p><strong>D. Changes to this Notice of Privacy Practices</strong></p>
      <p>We reserve the right to amend this Notice of Privacy Practices at any time in the future. Until such amendment is made, we are required by law to comply with the terms of this Notice currently in effect. After an amendment is made, the revised Notice of Privacy Protections will apply to all protected health information that we maintain, regardless of when it was created or received. We will post the current notice on our website.</p>
      <p><strong>E. Complaints</strong></p>
      <p>Complaints about this Notice of Privacy Practices or how Skin MD Now handles your health information should be directed to our Privacy Officer listed at the top of this Notice of Privacy Practices.</p>
      <p>If you are not satisfied with the manner in which this office handles a complaint, you may submit a formal complaint to:</p>
      <p>Velveta Howell, Regional Manager Office for Civil Rights<br>
                U.S. Department of Health and Human Services<br>
                999 18th Street, Suite 417<br>
                Denver, CO 80202<br>
                Voice Phone (800) 368-1019<br>
                FAX (303) 844-2025<br>
                TDD (800) 537-7697<br>
                OCRMail@hhs.gov</p>
      <p>The complaint form may be found at <a href="www.hhs.gov/ocr/privacy/hipaa/complaints/hipcomplaint.pdf" target="_blank">www.hhs.gov/ocr/privacy/hipaa/complaints/hipcomplaint.pdf</a>. You will not be penalized in any way for filing a complaint.</p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
      <h2>Skin<sup>md</sup> Now Terms of Service</h2>
      <p>Effective:  January 1, 2013<br>
                Last updated: April 29, 2013</p>
      <h3> <strong>PLEASE READ  THESE TERMS OF SERVICE CAREFULLY.</strong> </h3>
      <p>Your use of the Skin<sup>md</sup> Now website, app (application), chat, text, social media, including any use of Skin<sup>md</sup> Now by telephone, email, fax, is conditioned upon your acceptance of the Terms of Service. By using Skin<sup>md</sup> Now, you agree to be bound by the Terms of Service and any other agreements. If you, or any third party, do not agree to these Terms of Service, you are NOT authorized to access or use Skin<sup>md</sup> Now.</p>
      <h3> <strong>IMPORTANT  INFORMATION ABOUT YOUR USE OF THE ONLINE SERVICES</strong></h3>
      <p>DO NOT USE Skin<sup>md</sup> NOW FOR EMERGENCY MEDICAL NEEDS. If you experience a medical emergency, before or after using Skin<sup>md</sup> Now, call 911, or go to the nearest emergency room immediately. Skin<sup>md</sup> Now does not warrant any specific Turn-around Time -- time from when your request is submitted until when you receive a reply from a selected Provider (physician or non-physician health care professional).</p>
      <p>Services offered by Skin<sup>md</sup> Now are not intended to replace your relationship with your regular health care practitioners. Neither Skin<sup>md</sup> Now nor any of its contractors, licensors or suppliers shall be liable for any damages or losses related to any medical diagnosis, treatment or professional advice obtained from a Provider, nor for any damages or losses related to any other information obtained on Skin<sup>md</sup> Now.</p>
      <p>By using Skin<sup>md</sup> Now, user provides informed consent to Skin<sup>md</sup> Now and its Providers to use user’s health information for purposes of Treatment, Payment and Healthcare Operations.</p>
      <p>The content on Skin<sup>md</sup> Now should not be considered medical advice. You should always talk to a Provider or other appropriately qualified health care professional for diagnosis and treatment, including information regarding which drugs or treatment may be appropriate for you. None of the content from Skin<sup>md</sup> Now represents or warrants that any particular drug or treatment is safe, appropriate, or effective for you. Without limitation, Skin<sup>md</sup> Now does not recommend or endorse any specific tests, Providers, Consumer Advisors, medications, products or procedures.</p>
      <p>User is solely responsible for follow-up with a health care professional in a timely manner. </p>
      <h3><strong>HIPAA POLICY AND CONSENT FORM </strong></h3>
      <p>The Health Insurance Portability and Accountability Act (HIPAA) provides safeguards to protect your privacy. Implementation of HIPAA requirement officially began on April 14, 2003. Many of the policies have been our practice for years. This is an abbreviated version; however, the complete text is available on the U.S. Department of Health and Human Services web site: www.hhs.gov.</p>
      <p>HIPAA states that there are rules and restrictions on who may see or be notified of your Protected Health Information (PHI). These restrictions do not include the normal interchange of information necessary to provide you with medical services.</p>
      <p>User’s information will be kept confidential except as is necessary to provide services or to ensure that all administrative matters related to your care are handled appropriately. This specifically includes the sharing of information with other healthcare providers, laboratories, pharmacies, payment processors, scheduling staff and health insurance payers as is necessary and appropriate for your care.</p>
      <p>It is the policy of Skin<sup>md</sup> Now to update users of changes in their request’s status. Skin<sup>md</sup> Now may do this by telephone, or e-mail, U.S. mail, or by any means convenient for Skin<sup>md</sup> Now and/or as requested by you. Skin<sup>md</sup> Now may send user other communications informing you of changes to Skin<sup>md</sup> Now policy and new technology that user might find valuable or informative.</p>
      <p>Skin<sup>md</sup> Now agrees to provide users with access to their records in accordance with state and federal laws. User understands and agrees to inspections of and review of documents which may include PHI by government agencies or insurance payers in normal performance of their duties.</p>
      <p>Skin<sup>md</sup> Now may change, add, delete or modify any of these provisions to better serve the needs of the Skin<sup>md</sup> Now and the user. User has the right to request restrictions in the use of your protected health information as the law permits. User’s confidential information will not be sold for any reason.</p>
      <p> User’s use of Skin<sup>md</sup> Now will indicate that user has read the HIPAA information and consents to the guidelines set forth in the Health Insurance Portability and Accountability Act. </p>
      <h3><strong>PRIVACY POLICY </strong></h3>
      <strong>1. Introduction </strong>
      <p>This statement discloses the privacy policies and practices for the Online Services. Your use of Skin<sup>md</sup> Now indicates your acceptance of the terms of this Privacy Policy.</p>
      <p>Skin<sup>md</sup> Now is constantly innovating and implementing new features in its website to provide the best possible experience. This policy will continue to evolve as our website evolves.</p>
      <p>Skin<sup>md</sup> Now contains links to other sites. However, Skin<sup>md</sup> Now is not responsible for the privacy practices or the content of such links. </p>
      <strong>2. Authorization, Consent and Acknowledgement </strong>
      <p>In order to participate in the Skin<sup>md</sup> Now Services, user will need to provide certain personal and medical information (PHI) about user either to Skin<sup>md</sup> Now or to a Provider without limitation, and providing Skin<sup>md</sup> Now directly with your name, e-mail address, mailing address, and phone number. Skin<sup>md</sup> Now will share user’s PHI with Providers. Likewise, Providers will share user’s PHI with Skin<sup>md</sup> Now. </p>
      <p>By using Skin<sup>md</sup> Now, user consents to release of PHI.</p>
      <p>User may choose not to share PHI; however, user may not be able to utilize some features of Skin<sup>md</sup> Now, including the Online Services furnished by Providers. All Providers have represented to Skin<sup>md</sup> Now that they will comply with all federal and state privacy and security laws applicable to user’s interactions with such Providers. However, Skin<sup>md</sup> Now is not responsible for any violations of those laws by individual Providers.</p>
      <p>If you are a user who is submitting information that is the PHI of another person, user acknowledges that he/she has obtained informed consent of this other person prior to such a submission of PHI.</p>
      <p> Skin<sup>md</sup> Now may obtain personal data from your health plan, laboratory, pharmacy, pharmacy benefits manager and other third parties. That data will be subject to the same privacy and security policies as the PHI that you submit to us.</p>
      <p>Skin<sup>md</sup> Now will not share your PHI with any other third parties without your express permission, except as otherwise permitted by these Terms of Service or as required by law or a court.</p>
      <p>Skin<sup>md</sup> Now will use your email address as the primary means to reset your username and password. Your email address must not be shared with any other third party. On occasion, we may contact you to inform you of product improvements, assess consumer satisfaction, or solicit your feedback for continuous improvement of our Online Services, and for similar reasons. From time to time, Skin<sup>md</sup> Now may combine, in a non-identifiable format, some of the PHI you provide with information from others to create aggregate reports. This type of information is essential for us to operate and identify ways to improve our services and may also be used for general public health purposes. Aggregate data does not contain any information that could be used to contact or identify you.</p>
      <p>The data Skin<sup>md</sup> Now collects via the Skin<sup>md</sup> Now website is audited internally. It also helps Skin<sup>md</sup> Now troubleshoot a problem for user and/or Provider. This information is accessed only by authorized Skin<sup>md</sup> Now representatives.</p>
      <p>By using Skin<sup>md</sup> Now, user authorizes the use of photographs or pathology slides for medical research, education, science, insurance providers or marketing. Safeguards will be taken to maintain patient confidentiality and patient identity. However, in certain, limited, circumstances, Skin<sup>md</sup> Now may use and disclose user’s PHI without consent or authorization if Skin<sup>md</sup> Now obtains approval through a special process to ensure that such research poses little risk to your privacy. In any case, Skin<sup>md</sup> Now would never allow researchers to use your name or identity publicly. Skin<sup>md</sup> Now may also release user’s health information without user’s written authorization to people who are preparing for a future research project, so long as no personally identifiable information is disclosed.</p>
      <p>If user would like to delete or modify user’s PHI, please contact Customer Support at info@skinmdnow.com. User has the right to ask that Skin<sup>md</sup> Now limit how it uses and discloses user’s PHI. Skin<sup>md</sup> Now will consider user’s request, but are not legally required to accept it. If Skin<sup>md</sup> Now accepts user’s request, Skin<sup>md</sup> Now will put any limits in writing and abide by them except in emergency situations. User may not limit the uses and disclosures that Skin<sup>md</sup> Now is legally required or allowed to make.</p>
      <p>This authorization will expire when user revokes it in writing. User has the right to revoke this authorization in writing except as Skin<sup>md</sup> Now has acted in reliance upon this authorization. User’s written revocation must be submitted to: info@skinmdnow.com </p>
      <h3>WAIVER FOR NON-COVERED SERVICES / ADVANCE BENEFICIARY NOTICE OF NONCOVERAGE</h3>
      <p>By using the services of Skin<sup>md</sup> Now, user acknowledges that Skin<sup>md</sup> Now’s services are not covered by your healthcare insurance, and user’s healthcare insurance will not be billed for such services. User agrees voluntarily, and under no duress, to be responsible for any fees incurred from user’s use of Skin<sup>md</sup> Now services.</p>
      <h3>ACCURACY AND COMPLETENESS OF INFORMATION </h3>
      <p>You, the User, are solely responsible for ensuring that information provided to Skin<sup>md</sup> Now is both accurate and complete. You acknowledge that information accuracy and completeness are critical for the efficient and legal provision of Skin<sup>md</sup> Now services. Covered information includes, but is not limited to, name, gender, date of birth, state of residence, billing information, phone number, drug allergies, personal and family medical, pharmacy information, and any information, or photographs, related to Condition (reason for submitting request).</p>
      <h3><strong>AVAILABLE PROVIDERS</strong></h3>
      <p>User may select a Provider based on specialty, location and/or fee. User must be a resident of the state or physically present in the state, in which the user-selected Provider is licensed to practice. Providers are independent (i.e., not employed by, or under contract to, Skin<sup>md</sup> Now to provide services on its behalf).</p>
      <h3><strong>SELECTING A PROVIDER</strong></h3>
      <p>Skin<sup>md</sup> Now does not make any representations or warranties about the Providers’ training or skill.</p>
      <p> Users are ultimately responsible for selecting a Provider from the list of available Providers.  Skin<sup>md</sup> Now will not select a Provider for you. In addition, Skin<sup>md</sup> Now does not guarantee the continued availability of any certain Provider, nor will Skin<sup>md</sup> Now be held liable for not providing access to a Provider in a user’s state, or any specific Provider. </p>
      <h3><strong>EXCHANGE OF  INFORMATION</strong></h3>
      <p>The medical advice or health-related information provided through the Skin<sup>md</sup> Now and Physician Services is based on user’s personal health data as provided by the user, or on personal health data that the user authorizes the Provider and Skin<sup>md</sup> Now to obtain. User understands that you may choose to give access to only certain portions of user’s medical records, but that doing so may interfere with, or harm, user’s care. User may not enter or disclose any information, health-related or otherwise, about another person without their permission.</p>
      <h3><strong>ACCOUNT ENROLLMENT  AND YOUR REQUIREMENTS</strong> </h3>
      <p>To access Skin<sup>md</sup> Now, you must establish an individual user account ("Account"), by providing certain information. With the exception of subaccounts (as described below) established for minor children of whom you are a parent or legal guardian, or for health care professionals, you agree that you will not create more than one Account, or create an account for anyone other than yourself without first receiving permission from the person for whom you are creating an account. In exchange for your use of Skin<sup>md</sup> Now and, if applicable, in order for Physicians to send notices to you, you agree to: (i) provide true, accurate, current and complete information about yourself; and (ii) each time you log on, maintain and promptly update such account information to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or we have reasonable grounds to suspect that such account information is untrue, inaccurate, not current or incomplete, we reserve the right to suspend or terminate your Account and refuse any and all current or future use of Skin<sup>md</sup> Now or any portion thereof.</p>
      <h3><strong>ACCOUNT  SECURITY</strong></h3>
      <p>Upon enrollment, you will establish a unique username and password (which may be changed from time to time). Your Account, username, and password are personal to you and you are responsible for maintaining the security of passwords associated with the Account you use to access Skin<sup>md</sup> Now. You are responsible for selecting a “strong” password (with a combination of numbers, symbols, and upper and lower case letters), and safeguarding your password. You should never allow any other person to access your Account on your behalf. Skin<sup>md</sup> Now will not be held liable for any damages resulting from unauthorized access to your account. You assume responsibility for all unauthorized use of your Account username, or password, and you must promptly notify Skin<sup>md</sup> Now of all actual or suspected unauthorized use. To permit you to access Skin<sup>md</sup> Now on behalf of a minor child of whom you are a parent or legal guardian, or caretaking health care professional, you may establish one or more subaccounts in connection with your Account. Any such Skin<sup>md</sup> Now -authorized sub-account(s) shall be deemed an Account for purposes of these Terms of Service.</p>
      <h3><strong>ACCEPTABLE USE</strong></h3>
      <p>Skin<sup>md</sup> Now grants you permission to use their services for your personal, non-commercial purposes. Your use is limited as follows:</p>
      <p>You will not use Skin<sup>md</sup> Now for unlawful purposes, and you will comply with all applicable laws and regulations while using the Skin<sup>md</sup> Now Services.</p>
      <p>You may not distribute, modify, copy (except as set forth in these Terms of Service), transmit, display, reuse, reproduce, publish, license, create derivative works from, transfer, translate, sell, reverse engineer, decompile or disassemble, or otherwise use any services of Skin<sup>md</sup> Now without Skin<sup>md</sup> Now’s explicit, written permission.</p>
      <p>You will not post or transmit any threatening, false, misleading, abusive, libelous, pornographic, or profane material.</p>
      <p>You will not incorporate any code into the code of Skin<sup>md</sup> Now or use Skin<sup>md</sup> Now to post or transmit any computer code that is harmful, or may be or is intended to, damage or to monitor the use or operation of any services offered by Skin<sup>md</sup> Now or any other user of the Skin<sup>md</sup> Now.</p>
      <p>You will not use Skin<sup>md</sup> Now to harvest or collect personally identifiable information about its users, physicians, non-physician users, or other health care professionals, of Skin<sup>md</sup> Now or any other information concerning the services of Skin<sup>md</sup> Now.</p>
      <p>You will not allow any other person or entity to use your identification to post or view comments, or to otherwise access or use the services of Skin<sup>md</sup> Now.</p>
      <p>You will not infringe the copyright or other intellectual property rights of others or Skin<sup>md</sup> Now, or violate the privacy or publicity rights of others or Skin<sup>md</sup> Now. </p>
      <h3><strong>ACCOUNT  UTILIZATION</strong></h3>
      <p>You must not interfere with, disrupt, or attempt to interfere with or disrupt the operation of the website or app (application) through which you access the services of Skin<sup>md</sup> Now, and you must abide by the security policies adopted by Skin<sup>md</sup> Now. You acknowledge and agree that, for security and other purposes, Skin<sup>md</sup> Now may monitor utilization of your Account. We are monitoring utilization in order to ensure appropriate use of the Skin<sup>md</sup> Now services, including, but not limited to, limitations set forth in the section titled "Acceptable Use" or as otherwise brought to our attention by a Physician or Provider.</p>
      <h3><strong>CHARGES</strong></h3>
      <p>You will be informed of the fee to be charged when you select a Physician. You will be responsible for providing a valid credit card number, expiration date, and card security code at the time you submit a request, or purchase a product.</p>
      <p>You understand that the fees may be changed from time to time, but that the Skin<sup>md</sup> Now App will reflect current fees. You understand that products or services may not be provided if the credit card information you provide is incomplete, inaccurate or invalid. </p>
      <h3><strong>RESPONSIBILITY  FOR APPLICABLE FEES &amp; REFUND POLICY</strong></h3>
      <p>If you are charged for a request submitted to a Provider but you do not receive a reply, please submit a claim within 30 days to info@skinmdnow.com. In all other circumstances, please be aware that by submitting a request to a Provider, you are agreeing to pay the Provider's listed fee.</p>
      <p>You are solely responsible for all fees for the Skin<sup>md</sup> Now services. You will still be responsible for paying the charged fee even if you provided poor quality, incomplete, inaccurate, misleading, not useful information (including photographs) in the request submitting by you or for you. Hence, you will still be responsible for paying the charged fee if you upload photographs which are deemed to be of poor quality or not useful by the Provider you have selected to evaluate your request. You will be responsible for paying the charged fee irrespective of Turn-around Time, or change in your Condition before or after you receive a reply from a Provider.</p>
      <p>You are free to seek payment from your health plan. Please check with your health plan to determine if Skin<sup>md</sup> Now services may be covered. You agree that you will not use the Skin<sup>md</sup> Now for any service that must be provided to you by your regular physician as a follow-up to an in-office visit, at no additional charge to you or your health care plan, as required by your health care plan. If you do use the Online Services in such a situation, and it is ultimately determined that the Provider may not bill you for its services provided through the Online Services, you understand that you will still be liable for the component of the charge attributable to the Administrative Fee. </p>
      <h3><strong>VIOLATION OF  THESE TERMS OF SERVICE</strong></h3>
      <p>You acknowledge that your access to Skin<sup>md</sup> Now services shall be immediately suspended and may be terminated if you violate any provision of these Terms of Service. You agree that a violation of these Terms of Service by you will result in irreparable injury that will entitle Skin<sup>md</sup> Now to obtain a court order prohibiting you from using the Skin<sup>md</sup> Now services.</p>
      <h3><strong>OPERATION AND  RECORD RETENTION</strong></h3>
      <p>Skin<sup>md</sup> Now reserves complete and sole discretion with respect to the operation of its services. Skin<sup>md</sup> Now may withdraw, suspend or discontinue any functionality or feature of its services with or without notice. Skin<sup>md</sup> Now has entered into arrangements with the Providers to allow them access to any of your data or records that they may need to render services of Skin<sup>md</sup> Now. At the completion of each transaction, you will receive a report electronically. That will be your only record and it is your responsibility to maintain that for your records. Skin<sup>md</sup> Now is not responsible to you for maintaining any data, including photographs, arising from use of the Skin<sup>md</sup> Now.</p>
      <h3><strong>LINKS</strong></h3>
      <p>Areas of the Online Services may contain links to other websites. Please note that when you click on any of these links, you are entering another website over which Skin<sup>md</sup> Now has no responsibility or control. The inclusion of any link does not imply affiliation, endorsement or adoption by Skin<sup>md</sup> Now of the linked website or any medical or other information contained therein. You are encouraged to read the terms of service, data-gathering practices and privacy policies of all linked websites as they may materially differ from ours. Skin<sup>md</sup> Now is not responsible for any loss or damage of any sort due to the presence or use of any such links.</p>
      <h3><strong>ADVERTISEMENTS</strong></h3>
      <p>Skin<sup>md</sup> Now may display advertisements from third parties. Such advertisements do not constitute or imply an endorsement, sponsorship, or recommendation by Skin<sup>md</sup> Now, of the third party, the third-party advertisement, or the information in the advertisement. Skin<sup>md</sup> Now is not responsible for the availability of any product, service, website, or anything displayed in the advertisement, and is not responsible or liable for, any such advertisement, its content, or the privacy policy, practices, and acts or omissions of the third party associated with the advertisement.</p>
      <h3><strong>INTELLECTUAL  PROPERTY</strong></h3>
      <p>All of the information, text, graphics, trademarks, logotypes, data and data compilations accessible through the Skin<sup>md</sup> Now services are the property of Skin<sup>md</sup> Now and its suppliers and are protected by U.S. and international copyright, trademark and other intellectual property rights laws. You may use the Skin<sup>md</sup> Now services solely for your personal, non-commercial use. If any portion of the Terms of Service is violated, the limited license for your usage of Skin<sup>md</sup> Now is automatically revoked.</p>
      <h3><strong>DISCLAIMERS</strong></h3>
      <p>Access to the online services and the content is provided "as is" and "as available" without any warranty of any kind, express or implied. Skin<sup>md</sup> Now disclaims all warranties of any kind, either express or implied, including but not limited to any implied warranties of title, merchantability, fitness for a particular purpose or non-infringement.</p>
      <p>Without limiting the foregoing, Skin<sup>md</sup> Now does not warrant that access to the Skin<sup>md</sup> Now services will be uninterrupted or error-free, or that defects, if any, will be corrected; nor does  Skin<sup>md</sup> Now  make any representations about the accuracy, reliability, currency, quality, completeness, usefulness, performance, security, legality or suitability of the online services or any of the information contained therein. You expressly agree that your use of Skin<sup>md</sup> Now services and your reliance upon any of its contents is at your sole risk. </p>
      <h3><strong>LIMITATION OF  LIABILITY</strong></h3>
      <p>Except as prohibited by law, and without limitation: </p>
      <p>Skin<sup>md</sup> Now shall not be liable for the acts or omissions of any of Providers. </p>
      <p>You shall be solely and fully responsible for any damage to Skin<sup>md</sup> Now and the online services or any computer system, any loss of data, or any improper use or disclosure of information on the online services caused by you or any person using your user name or password. Skin<sup>md</sup> Now cannot and does not assume any responsibility for any loss, damages or liabilities arising from the failure of any telecommunications infrastructure, or the internet or for your misuse of any of the advice, ideas, information, instructions or guidelines accessed through online services.</p>
      <p>In the event of any problem or dissatisfaction with the Skin<sup>md</sup> Now services, your sole remedy is to cease using the Skin<sup>md</sup> Now services. Under no circumstances shall Skin<sup>md</sup> Now, or any Skin<sup>md</sup> Now licensor or supplier, be liable in any way for your use of the Skin<sup>md</sup> Now services or any of its content.</p>
      <p> Under no circumstances shall Skin<sup>md</sup> Now, or its licensors or suppliers, Providers be liable for any punitive, exemplary, consequential, incidental, indirect or special damages, even if we or they have been advised of the possibility of such damages.</p>
      <p>You hereby release, indemnify and hold Skin<sup>md</sup> Now, its licensors and suppliers, Providers harmless from any and all claims, demands, and damages of every kind and nature arising out of or in any way connected with your use of Skin<sup>md</sup> Now services or your breach of any of your obligations. </p>
      <h3><strong>ERRORS</strong></h3>
      <p>The Skin<sup>md</sup> Now Services may contain typographical errors or other errors or inaccuracies and may not be complete or current. Skin<sup>md</sup> Now reserves the right to correct any errors, inaccuracies or omissions and to change or update information at any time without prior notice. Skin<sup>md</sup> Now does not guarantee that any errors, inaccuracies or omissions will be corrected.</p>
      <h3><strong>INTERNATIONAL  USE</strong></h3>
      <p>The Skin<sup>md</sup> Now Services are designed for and intended for users in the United States. Skin<sup>md</sup> Now makes no representation that the information and services provided on the Skin<sup>md</sup> Now Services are applicable to, appropriate for, or available outside the United States. Accessing the Skin<sup>md</sup> Now Services from states, nations or territories where the content is illegal is prohibited.</p>
      <h3><strong>MISCELLANEOUS</strong></h3>
      <p>LIMITATION, SUSPENSION AND TERMINATION OF USE</p>
      <p>Skin<sup>md</sup> Now may refuse, limit, suspend or terminate user’s access to and use of the Online Services at any time, and without notice, as Skin<sup>md</sup> Now considers appropriate or necessary in its sole discretion, including but not limited to (i) security, (ii) alleged or suspected breach of these Terms of Service, or (iii) the protection of intellectual property. Skin<sup>md</sup> Now may also impose limits on certain features and functions of the Skin<sup>md</sup> Now Services or otherwise restrict your access to the Online Services without notice or liability. The provisions of these Terms of Service will remain in effect after termination or suspension of your access to the Skin<sup>md</sup> Now Services. You may terminate your use of the Skin<sup>md</sup> Now Services at any time, however you will remain responsible for all charges you have incurred prior to your termination. </p>
      <h3><strong>GOVERNING LAW</strong></h3>
      <p>Skin<sup>md</sup> Now is created and controlled in the State of South Dakota. As such, the laws of the State of South Dakota will govern agreements, terms and conditions, without giving effect to any principles of conflicts of laws. Skin<sup>md</sup> Now reserves the right to make changes to its site and these terms at any time.  Users hereby irrevocably and unconditionally consent to submit to the exclusive jurisdiction of the Courts of the State of South Dakota and of the United States of America  for any litigation arising out of or relating to use of Skin<sup>md</sup> Now and agrees not to commence any litigation relating thereto except in such courts, waives any objection to the laying of venue of any such litigation in the South Dakota Courts and agrees not to plead or claim in any South Dakota Court that such litigation brought therein has been brought in an inconvenient forum.</p>
      <h3><strong>SEVERABILITY</strong></h3>
      <p>To the extent possible, these Terms of Service will be read together with any applicable statute or rule of law. Thereafter, if any of the Terms of Service conflict with any applicable statute or rule of law, the affected terms and conditions will be deemed inoperative but the remaining portions will remain in full force and effect.</p>
      <h3><strong>WAIVER</strong></h3>
      <p>No failure by either party to take any action or assert any right under these Terms of Service will be deemed to be a waiver of that right in the event of the continuation or repetition of the circumstances giving rise to that right.</p>
      <h3><strong>ENTIRE  AGREEMENT</strong></h3>
      <p>These Terms of Service and the state-specific notifications below constitute the entire agreement between you and Skin<sup>md</sup> Now and govern your use of the website and Online Services. These Terms of Service supersede any and all prior agreements between you and Skin<sup>md</sup> Now regarding your use of the website and Online Services.</p>
      <h3><strong>CHANGES TO  THESE TERMS OF SERVICE</strong></h3>
      <p>Please keep a copy of these Terms of Service. Skin<sup>md</sup> Now may change the Terms of Service at any time. The most current version of these Terms of Service can be accessed at any time by selecting the Terms of Service link on Skin<sup>md</sup> Now’s website. The last date these Terms of Service were updated is listed above.</p>
      <p><strong>You represent and warrant that you are at least 18 years of age and possess the legal right and ability, on behalf of yourself or a minor child of whom you are a parent or legal guardian, or health care provider, to agree to these Terms of Service and to use this website in accordance with these Terms of Service.</strong></p>
      <h3><strong>CUSTOMER  SERVICE</strong></h3>
      <p><strong>If you have any questions, concerns or complaints about the Skin<sup>md</sup> Now services, please feel free to contact Skin<sup>md</sup> Now Customer Relations via a link on Skin<sup>md</sup> Now’s website. </strong><strong></strong></p>
      <h2>LEGAL  NOTICES</h2>
      <h3><strong>E-SIGN  DISCLOSURE AND CONSENT</strong></h3>
      <p>This Electronic Disclosure and Consent ("Disclosure") applies to any privacy or other notices, disclosures, reports, documents, communications, or other records provided by Skin<sup>md</sup> Now, a Provider, or Consumer Advisor regarding the Online Services (collectively, "Notices"). By assenting to these Terms of Service, you agree that Skin<sup>md</sup> Now and Physicians (i) may provide you with any Notices that they may choose to send or make available to you, to the extent allowed by law, in electronic form and (ii) that you have been able to read this Disclosure and have access to the software and hardware (described below) necessary to access the Notices.</p>
      <p>All Notices that Skin<sup>md</sup> Now or a Provider or Consumer Advisor elect to provide to you in electronic form will be provided either (i) via e-mail to the address that you provided upon enrollment or (ii) by posting the Notice on the website by which you access the Online Services. The delivery of any Notice is effective when sent, regardless of how it is delivered to you, whether you read the Notice when you receive it, or whether you actually receive the delivery.</p>
      <p>Consent is a condition to the use of Skin<sup>md</sup> Now Online Services. If at any time you decide to withdraw your consent, you may do so by canceling or discontinuing your use of the Skin<sup>md</sup> Now Services. Should you subsequently resume use of the Online Services, you will be deemed to have ratified your original consent.</p>
      <p>Skin<sup>md</sup> Now may treat the provision of an invalid e-mail address, or the subsequent malfunction of a previously valid e-mail address, as a withdrawal of your consent to receive Notices in electronic form. Skin<sup>md</sup> Now will not impose any fee to process the withdrawal of your consent to receive Notices in electronic form; however, your access to and use of the Skin<sup>md</sup> Now Services may be terminated. Any withdrawal of your consent to receive Notices in electronic form will be effective only after we have a reasonable period of time to process your withdrawal.</p>
      <p>Consistent with the section entitled "Account Enrollment and Your Requirements", it is your responsibility to provide true, accurate, current, and complete information about yourself, and to maintain and update promptly such information. You can update your information (e.g., your e-mail address) through the website (click on "My Account").</p>
      <p>In order to access, view, and retain electronic Notices that Skin<sup>md</sup> Now makes available to you, you must: (i) have access to an Internet service account, (ii) an e-mail account (and any necessary e-mail software),  (iii) have access to a personal computer, operating system, and telecommunications connections to the Internet capable of receiving, accessing, displaying, and either printing or storing Notices received from Skin<sup>md</sup> Now in electronic form via a plain text-formatted e-mail or by access to the website using your Internet browser application (e.g., Internet Explorer, Firefox, Safari) and (iv) have access to a personal smart phone.</p>
      <p>Skin<sup>md</sup> Now may charge you a reasonable service charge, of which we will have provided you prior notice, for the delivery of paper copies of any Notice provided to you electronically pursuant to this authorization. Skin<sup>md</sup> Now reserves the right, but assumes no obligation, to provide a paper (instead of electronic) copy of any Notice that you have authorized us to provide electronically. </p>
      <p>All Notices in either electronic or paper format from us to you will be considered "in writing." You should print or download for your records a copy of this Disclosure and any other Notice that is important to you.</p>
      <p>You acknowledge and agree that your consent to electronic Notices is being provided in connection with a transaction affecting interstate commerce that is subject to the federal Electronic Signatures in Global and National Commerce Act, and that you and Skin<sup>md</sup> Now both intend that the Act apply to the fullest extent possible to validate our ability to conduct business with you by electronic means.</p>
      <p>Skin<sup>md</sup> Now reserves the right, in its sole discretion, to discontinue the provision of your electronic Notices, or to terminate or change the terms and conditions on which it provides electronic Notices. Skin<sup>md</sup> Now will provide you with notice of any such termination or change as required by law. </p>
      <h2> STATE SPECIFIC  NOTIFICATIONS</h2>
      <h3><strong>FOR CALIFORNIA  RESIDENTS</strong></h3>
      <p>You or your legal representative retains the option to withhold or withdraw consent to receive health care services via the Online Services at any time without affecting your right to future care or treatment nor risking the loss or withdrawal of any benefits to which you or your legal representative would otherwise by entitled.</p>
      <p>All existing confidentiality protections apply.</p>
      <p>All existing laws regarding patient access to medical information and copies of medical records apply. 
                Dissemination of any of any of your identifiable images or information from the telemedicine interaction to researchers or other entities shall not occur without your consent.</p>
      <p>All provisions of these Terms of Service, including your informed consent to receive services via the Online Services are for the benefit of the treating Provider as well as for your benefit. </p>
      <p><strong>NOTICE</strong> <br>
                <strong>Medical doctors  are licensed and regulated by the Medical Board of California</strong> <br>
                <strong>(800) 632-2322</strong> <br>
                <strong>www.mbc.ca.gov</strong> </p>
      <h3><strong>FOR FLORIDA  RESIDENTS</strong></h3>
      <p>Each Provider's hours are variable. To access a Provider's in-office schedule, contact that Provider’s office. </p>
      <h3> <strong>FOR GEORGIA  RESIDENTS</strong></h3>
      <p> <strong>Patient Right  to Know</strong></p>
      <p>The patient has the right to file a grievance with the Georgia Composite Medical Board concerning the physician, staff, office, and treatment received. The patient should either call the Board with such a complaint or send a written complaint to the Board. The patient should be able to provide the physician or practice name, the address, and the specific nature of the complaint.</p>
      <h3><strong>FOR INDIANA  RESIDENTS</strong></h3>
      <p>Unless your Provider specifically discloses otherwise, with the exception of charges for services delivered to patients, Providers do not have any financial interest in any information, products, or services offered through Skin<sup>md</sup> Now.</p>
      <p>I expressly consent to Providers forwarding my patient identifiable information to Skin<sup>md</sup> Now or Physician's designee.</p>
      <p>I agree that I will hold harmless Skin<sup>md</sup> Now and each Provider for any loss of information due to a technical failure. </p>
      <p><strong>Notice  Concerning Complaints</strong></p>
      <p>You may either file a complaint online or download the appropriate complaint form found at http://www.indianaconsumer.com/filecomplaint.asp. If downloading, you must complete, sign, print, and mail it, along with copies of all relevant supporting documentation to:</p>
      <p>Consumer Protection Division <br>
                Office of the Indiana Attorney General <br>
                302 W. Washington St., 5th Floor <br>
                Indianapolis, IN 46204 </p>
      <p>You can also request a complaint form by calling 800-382-5516 or 317-232-6330. </p>
      <h3><strong>FOR KANSAS  RESIDENTS</strong></h3>
      <p>Notice to  Patients: Required Signage for K.A.R. 100-22-6<br>
                Prepared by the State Board of Healing Arts<br>
                April 5, 2007</p>
      <p><strong>NOTICE TO  PATIENTS</strong></p>
      <p>It is unlawful for any person who is not licensed under the Kansas Healing Arts Act to open or maintain an office for the practice of the healing arts in Kansas.</p>
      <p>Questions and concerns regarding this professional practice may be directed to: </p>
      <p><strong>KANSAS STATE  BOARD OF HEALING ARTS</strong></p>
      <p>235 S. Topeka Boulevard<br>
                Topeka, Kansas 66603<br>
                PHONE: (785) 296-7413<br>
                TOLL FREE: 1(888) 886-7205<br>
                FAX: (785) 296-0852<br>
                WEBSITE: www.ksbha.org</p>
      <h3><strong>FOR LOUISIANA  RESIDENTS</strong></h3>
      <p>The relationship between you and the Provider is not intended to replace the relationship between you and other providers.</p>
      <p>The relationship between you and the Provider is supplemental. Your primary care physician is responsible for your overall health care management. </p>
      <h3><strong>FOR MARYLAND  RESIDENTS</strong></h3>
      <p>Our procedure to verify the identification of the individual transmitting the communication:</p>
      <p>We verify your identification through the assignment and use of a unique username and password combination. When you sign into Skin<sup>md</sup> Now, your username and password identify you.</p>
      <p>Access to Skin<sup>md</sup> Now data is restricted through the use of unique usernames and passwords. The username and password assigned to you are personal to you and you must not share them with any other individual. </p>
      <h3><strong>FOR  MASSACHUSETTS RESIDENTS</strong></h3>
      <p>Written notice of patients' rights can be found in these Terms of Service.</p>
      <h3><strong>FOR OKLAHOMA  RESIDENTS</strong></h3>
      <p>You always retain the option to withhold or withdraw consent from obtaining health care services via Skin<sup>md</sup> Now. If you decide that you no longer wish to obtain health care services via Skin<sup>md</sup> Now, it will not affect your right to future care or treatment, nor will you risk the loss or withdrawal of any program benefits to which you would otherwise be entitled.</p>
      <p>Patient access to all medical information transmitted during a telemedicine interaction is guaranteed by the provider and copies of this information are available at stated costs, which shall not exceed the direct cost of providing the copies.</p>
      <p>All existing confidentiality protections apply.</p>
      <p>Dissemination of any of any of your identifiable images or identifiable information from the telemedicine interaction to researchers or other entities shall not occur without your consent.</p>
      <p>By agreeing with these Terms of Service, you acknowledge that you understand these provisions. </p>
      <h3><strong>FOR SOUTH  DAKOTA RESIDENTS</strong></h3>
      <p>Should any user wish to discuss fees or charges, he/she should contact Skin<sup>md</sup> Now.</p>
      <h3><strong>FOR TEXAS  RESIDENTS</strong></h3>
      <p>An additional in-person medical evaluation may be necessary to meet your needs if the Provider is unable to gather all the clinical information via Skin<sup>md</sup> Now to safely treat you.</p>
      <p>Unless your Provider specifically discloses otherwise, with the exception of charges for services delivered to patients, Providers do not have any financial interest in any information, products, or services offered through Skin<sup>md</sup> Now.</p>
      <p>The response time for emails, electronic messages and other communications can be found on your Provider's login page. </p>
      <p><strong>NOTICE  CONCERNING COMPLAINTS</strong></p>
      <p>Complaints about physicians, as well as other licensees and registrants of the Texas Medical Board, including physician assistants, acupuncturists, and surgical assistants may be reported for investigation at the following address: </p>
      <p>Texas Medical Board Attention: Investigations 333 Guadalupe, Tower 3, Suite 610 P.O. Box 2018, MC-263 Austin, Texas 78768-2018 </p>
      <p>Assistance in filing a complaint is available by calling the following telephone number: 1-800-201-9353</p>
      <p> For more information please visit our website at www.tmb.state.tx.us </p>
      <p><strong>AVISO SOBRE LAS  QUEJAS</strong></p>
      <p>Las quejas sobre médicos, así como sobre otros profesionales acreditados e inscritos en la Junta de Examinadores Médicos del Estado de Texas, incluyendo asistentes de médicos, practicantes de acupuntura y asistentes de cirugía, se pueden presentar en la siguiente dirección para ser investigadas:</p>
      <p> Texas Medical Board Attention: Investigations 333 Guadalupe, Tower 3, Suite 610 P.O. Box 2018, MC-263 Austin, Texas 78768-2018 </p>
      <p>Si necesita ayuda para presentar una queja, llame al: 1-800-201-9353
                Para obtener más información, viwebsite nuestro sitio web en www.tmb.state.tx.us </p>
      <h3><strong>FOR WISCONSIN  RESIDENTS</strong></h3>
      <p>Patients have the right to receive information regarding fees charged for a health care service, diagnostic test, or procedure identified by the patient and provided by the Provider. </p>
      <p>If you have any questions about Skin<sup>md</sup> Now’s Terms of Services, please contact us at info@skinmdnow.com.</p>
<br>
<br>
<br>
    

</div></div>

</body>
</html>
